//
//  GetImgursResponse.swift
//  PresentingServerDataInCollectionView
//
//  Created by Chaudhary Himanshu Raj on 29/01/18.
//  Copyright © 2018 Chaudhary Himanshu Raj. All rights reserved.
//

import Foundation

struct GetImgurResponse {
    
    
    var imgurs : [Imgur]
    
    // Now this init will be called in some function of NetworkingService's class, where we must do error handling, hence, if any error is generated by this init method, it will be caught by the catch block of the calling functions' do try catch block. Thus, throws used.
    init(json : JSON) throws {
        // print(json)
        
        // We need to put data from this response json into some object which have properties, declared based on the data we will be extracting from this json response. Like here in this case, we have Imgur struct for this purpose containing properties namely, [id, title, imageURL]
        guard let data = json["data"] as? [JSON] else { throw CustomError.someError  }
        
        // Now we need to map it to Imgur, so we use map.
        let imgurs = data.map{ Imgur(json : $0) }.flatMap{$0}
        self.imgurs = imgurs
    }
}
